import { createContext, useContext, useState, useEffect, useCallback } from "react";

// ─── Translation Dictionary ────────────────────────────────────────────────────
const translations = {
  // ── Navbar ──────────────────────────────────────────────────────────────────
  "nav.smartAgri":          { en: "Smart Agri",              ar: "زرعة الذكية" },
  "nav.signIn":             { en: "SIGN IN",                 ar: "تسجيل الدخول" },
  "nav.myProfile":          { en: "My Profile",              ar: "ملفي الشخصي" },
  "nav.settings":           { en: "Settings",                ar: "الإعدادات" },
  "nav.logout":             { en: "Logout",                  ar: "تسجيل الخروج" },
  "nav.accessAccount":      { en: "Access Account",          ar: "الوصول للحساب" },
  "nav.dashboard":          { en: "Dashboard",               ar: "لوحة التحكم" },
  "nav.smartFarming":       { en: "Smart Farming",           ar: "الزراعة الذكية" },
  "nav.productDashboard":   { en: "Product Dashboard",       ar: "لوحة المنتجات" },
  "nav.cropMarket":         { en: "Crop Market",             ar: "سوق المحاصيل" },
  "nav.agriShop":           { en: "Agri Shop",               ar: "متجر الزراعة" },
  "nav.marketplace":        { en: "Marketplace",             ar: "السوق" },
  "nav.experts":            { en: "Experts",                 ar: "الخبراء" },
  "nav.aiAssistant":        { en: "AI Assistant",            ar: "المساعد الذكي" },
  "nav.trackOrder":         { en: "Track Order",             ar: "تتبع الطلب" },
  "nav.trackOrders":        { en: "Track Orders",            ar: "تتبع الطلبات" },
  "nav.notifications":      { en: "Notifications",           ar: "الإشعارات" },
  "nav.adminPanel":         { en: "Admin Panel",             ar: "لوحة الإدارة" },
  "nav.admin":              { en: "Admin",                   ar: "الإدارة" },
  "nav.consultations":      { en: "Consultations",           ar: "الاستشارات" },
  "profile.sensorId":       { en: "Sensor ID",               ar: "رمز المستشعر" },
  "dash.addSensor":         { en: "Add Sensor",              ar: "إضافة مستشعر" },
  "dash.ventilationTelemetry": { en: "Ventilation Telemetry",  ar: "مراقبة التهوية" },
  "dash.fertilizerTelemetry":  { en: "Fertilizer Telemetry",   ar: "مراقبة التسميد" },
  "market.reviewsTitle":     { en: "Product Reviews",         ar: "تقييمات المنتج" },
  "market.reviews":          { en: "Reviews",                 ar: "تقييمات" },
  "market.leaveReview":      { en: "Leave a Review",          ar: "أضف تقييمك" },
  "market.editReview":       { en: "Edit Your Review",        ar: "تعديل تقييمك" },
  "market.writeCommentPlaceholder": { en: "Share your feedback about the product...", ar: "شاركنا برأيك وتجربتك للمنتج..." },
  "market.yourRating":       { en: "Your Rating",             ar: "تقييمك" },
  "market.submit":           { en: "Submit",                  ar: "إرسال" },
  "market.cancel":           { en: "Cancel",                  ar: "إلغاء" },
  "market.update":           { en: "Update",                  ar: "تحديث" },
  "market.noReviewsYet":     { en: "No reviews yet. Be the first to review!", ar: "لا توجد تقييمات بعد. كن أول من يضيف تقييماً!" },
  "market.pleaseLoginToReview": { en: "Please login to write a review.", ar: "برجاء تسجيل الدخول أولاً لإضافة تقييم." },
  "market.confirmDeleteReview": { en: "Are you sure you want to delete this review?", ar: "هل أنت متأكد من رغبتك في حذف هذا التقييم؟" },
  "prodDash.editProductTitle": { en: "Edit Product Details",  ar: "تعديل تفاصيل المنتج" },
  "prodDash.editProductDesc":  { en: "Update your product offerings in the marketplace.", ar: "تحديث عروض المنتجات الخاصة بك في السوق." },
  "nav.mainMenu":           { en: "Main Menu",               ar: "القائمة الرئيسية" },
  "nav.chat":               { en: "Chat",                    ar: "المحادثات" },
  "lang.toggle":            { en: "عربي",                   ar: "English" },

  // ── Home ────────────────────────────────────────────────────────────────────
  "home.hero.title1":       { en: "Smart Agriculture",       ar: "الزراعة الذكية" },
  "home.hero.title2":       { en: "For Modern Farmers.",     ar: "للمزارعين العصريين." },
  "home.hero.subtitle":     { en: "The ultimate AI-driven ecosystem for smart agriculture. Monitor sensors, consult experts, and trade in a unified digital landscape.", ar: "المنظومة المتكاملة للزراعة الذكية. راقب حقولك، استشر الخبراء، وتداول في بيئة رقمية موحدة." },
  "home.hero.getStarted":   { en: "Get Started",             ar: "ابدأ الآن" },
  "home.hero.explore":      { en: "Explore Marketplace",     ar: "استعرض السوق" },
  "home.stat.uptime":       { en: "Uptime",                  ar: "وقت التشغيل" },
  "home.stat.aiPred":       { en: "AI Prediction",           ar: "دقة الذكاء الاصطناعي" },
  "home.stat.yield":        { en: "Yield Increase",          ar: "زيادة الإنتاج" },
  "home.stat.security":     { en: "Security",                ar: "الأمان" },
  "home.modules":           { en: "Core Modules",            ar: "الوحدات الأساسية" },
  "home.sysPrefs":          { en: "System Preferences",      ar: "إعدادات النظام" },
  "home.ai.title":          { en: "Zar3a AI Engine",         ar: "محرك زرعة الذكي" },
  "home.ai.desc":           { en: "Identify crop diseases and get expert treatment plans instantly.", ar: "تشخيص أمراض المحاصيل والحصول على خطط علاجية فورية." },
  "home.ai.cta":            { en: "Open AI Hub",             ar: "افتح مركز الذكاء" },
  "home.telemetry.title":   { en: "Live Telemetry",          ar: "المراقبة الحية" },
  "home.telemetry.desc":    { en: "Review tracked market items, order state, and product flow from producers.", ar: "تتبع طلباتك ومسار المنتجات وتدفق البيانات من المنتجين." },
  "home.telemetry.cta":     { en: "Track Orders",            ar: "تتبع الطلبات" },
  "home.store.title":       { en: "Smart Store",             ar: "المتجر الذكي" },
  "home.store.desc":        { en: "Order seeds, tools, and fertilizers from verified suppliers.", ar: "اطلب البذور والأدوات والأسمدة من الموردين المعتمدين." },
  "home.store.cta":         { en: "Explore Store",           ar: "استعرض المتجر" },
  "home.expert.label":      { en: "Expert Concierge",        ar: "خدمة الخبراء" },
  "home.expert.title":      { en: "Consultation Hub",        ar: "مركز الاستشارات" },
  "home.expert.desc":       { en: "Connect with the best agricultural engineers for specialized guidance.", ar: "تواصل مع أفضل المهندسين الزراعيين للحصول على إرشادات متخصصة." },
  "home.expert.cta":        { en: "Find Expert",             ar: "ابحث عن خبير" },

  // ── Footer ──────────────────────────────────────────────────────────────────
  "footer.rights":          { en: "© 2024 Zar3a. All rights reserved.", ar: "© 2024 زرعة. جميع الحقوق محفوظة." },
  "footer.tagline":         { en: "Empowering farmers, connecting markets.", ar: "تمكين المزارعين، وربط الأسواق." },
  "footer.newsletter.title":{ en: "Join the Zar3a Network",  ar: "انضم إلى شبكة زرعة" },
  "footer.newsletter.sub":  { en: "Subscribe for weekly AI insights and agricultural market updates.", ar: "اشترك للحصول على رؤى الذكاء الاصطناعي وتحديثات السوق الزراعي أسبوعياً." },
  "footer.newsletter.email":{ en: "Enter your email",        ar: "أدخل بريدك الإلكتروني" },
  "footer.newsletter.btn":  { en: "Subscribe",               ar: "اشترك" },
  "footer.newsletter.done": { en: "Subscribed!",             ar: "تم الاشتراك!" },
  "footer.platform":        { en: "Platform",                ar: "المنصة" },
  "footer.resources":       { en: "Resources",               ar: "الموارد" },
  "footer.contact":         { en: "Contact & HQ",            ar: "التواصل والمقر" },
  "footer.privacy":         { en: "Privacy",                 ar: "الخصوصية" },
  "footer.darkMode":        { en: "Dark Mode",               ar: "الوضع الداكن" },
  "footer.lightMode":       { en: "Light Mode",              ar: "الوضع الفاتح" },

  // ── Login ───────────────────────────────────────────────────────────────────
  "login.home":             { en: "Home",                    ar: "الرئيسية" },
  "login.register":         { en: "Register",                ar: "إنشاء حساب" },
  "login.title":            { en: "Welcome",                 ar: "مرحباً" },
  "login.titleAccent":      { en: "Back",                    ar: "بعودتك" },
  "login.subtitle":         { en: "Access your agriculture hub", ar: "ادخل إلى منصتك الزراعية" },
  "login.emailLabel":       { en: "Email or Username",       ar: "البريد الإلكتروني أو اسم المستخدم" },
  "login.emailPlaceholder": { en: "farmer@zar3a.com or username", ar: "farmer@zar3a.com أو اسم المستخدم" },
  "login.passwordLabel":    { en: "Password",                ar: "كلمة المرور" },
  "login.keepSignedIn":     { en: "Keep me signed in",       ar: "ابقَ متصلاً" },
  "login.forgot":           { en: "Forgot?",                 ar: "نسيت؟" },
  "login.loading":          { en: "Loading...",              ar: "جاري التحميل..." },
  "login.signIn":           { en: "Sign In",                 ar: "تسجيل الدخول" },
  "login.newHere":          { en: "New here?",               ar: "مستخدم جديد؟" },
  "login.createAccount":    { en: "Create Account",          ar: "إنشاء حساب" },

  // ── Register ────────────────────────────────────────────────────────────────
  "reg.home":               { en: "Home",                    ar: "الرئيسية" },
  "reg.signIn":             { en: "Sign In",                 ar: "تسجيل الدخول" },
  "reg.title":              { en: "Join",                    ar: "انضم إلى" },
  "reg.subtitle":           { en: "The Future of Agricultural Intelligence", ar: "مستقبل الذكاء الزراعي" },
  "reg.step.account":       { en: "Account",                 ar: "الحساب" },
  "reg.step.role":          { en: "Role",                    ar: "الدور" },
  "reg.step.profile":       { en: "Profile",                 ar: "الملف" },
  "reg.fullName":           { en: "Full Name",               ar: "الاسم الكامل" },
  "reg.username":           { en: "Username",                ar: "اسم المستخدم" },
  "reg.email":              { en: "Email Address",           ar: "البريد الإلكتروني" },
  "reg.phone":              { en: "Phone Number",            ar: "رقم الهاتف" },
  "reg.password":           { en: "Password (min 8 chars)",  ar: "كلمة المرور (8 أحرف على الأقل)" },
  "reg.confirmPassword":    { en: "Confirm Password",        ar: "تأكيد كلمة المرور" },
  "reg.creating":           { en: "Creating account...",     ar: "جاري إنشاء الحساب..." },
  "reg.continue":           { en: "Continue",                ar: "متابعة" },
  "reg.saving":             { en: "Saving...",               ar: "جاري الحفظ..." },
  "reg.hasAccount":         { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "reg.whatDescribes":      { en: "What best describes you?", ar: "ما الذي يصفك بشكل أفضل؟" },
  "reg.completeProfile":    { en: "Complete your",           ar: "أكمل ملف" },
  "reg.profile":            { en: "profile",                 ar: "الشخصي" },
  "reg.back":               { en: "Back",                    ar: "رجوع" },
  "reg.finishing":          { en: "Finishing setup...",      ar: "جاري إتمام الإعداد..." },
  "reg.finishSetup":        { en: "Finish Setup",            ar: "إتمام الإعداد" },
  "reg.accountCreated":     { en: "Account Created!",        ar: "تم إنشاء الحساب!" },
  "reg.expertPending":      { en: "Your expert application is pending admin approval. We'll notify you soon.", ar: "طلب الخبير الخاص بك قيد مراجعة المسؤول. سنُعلمك قريباً." },
  "reg.welcome":            { en: "Welcome to Zar3a — your account is ready.", ar: "مرحباً بك في زرعة — حسابك جاهز." },
  "reg.goToLogin":          { en: "Go to Login",             ar: "الذهاب لتسجيل الدخول" },
  "reg.farmSize":           { en: "Farm Size (Acres)",       ar: "مساحة المزرعة (بالفدان)" },
  "reg.soilType":           { en: "Soil Type (required)",    ar: "نوع التربة (مطلوب)" },
  "reg.location":           { en: "Location (required)",     ar: "الموقع (مطلوب)" },
  "reg.tradeLicense":       { en: "Trade License Number",    ar: "رقم السجل التجاري" },
  "reg.bizLocation":        { en: "Business Location (required)", ar: "موقع النشاط التجاري (مطلوب)" },
  "reg.degree":             { en: "Academic Degree (required)", ar: "المؤهل الأكاديمي (مطلوب)" },
  "reg.experience":         { en: "Years of Experience (required)", ar: "سنوات الخبرة (مطلوبة)" },
  "reg.bio":                { en: "Bio (required)",          ar: "نبذة تعريفية (مطلوبة)" },
  "reg.uploadCv":           { en: "Upload CV / Credentials (optional)", ar: "رفع السيرة الذاتية (اختياري)" },
  "reg.expertWarning":      { en: "⚠️ Expert accounts require admin approval before activation.", ar: "⚠️ حسابات الخبراء تتطلب موافقة المسؤول قبل التفعيل." },
  "reg.buyerReady":         { en: "Your buyer account is ready to be activated!", ar: "حساب المشتري جاهز للتفعيل!" },
  "reg.buyerContinue":      { en: "Click Continue to finish setup.", ar: "انقر على متابعة لإتمام الإعداد." },
  "reg.selectRole":         { en: "Please select a role",    ar: "يرجى اختيار دور" },
  "reg.role.farmer":        { en: "Farmer",                  ar: "مزارع" },
  "reg.role.farmerDesc":    { en: "Grow crops & manage land", ar: "زراعة المحاصيل وإدارة الأراضي" },
  "reg.role.buyer":         { en: "Buyer",                   ar: "مشترٍ" },
  "reg.role.buyerDesc":     { en: "Purchase agricultural products", ar: "شراء المنتجات الزراعية" },
  "reg.role.supplier":      { en: "Supplier",                ar: "مورّد" },
  "reg.role.supplierDesc":  { en: "Supply tools & materials", ar: "توريد الأدوات والمواد" },
  "reg.role.expert":        { en: "Agro-Expert",             ar: "خبير زراعي" },
  "reg.role.expertDesc":    { en: "Specialist / Consultant", ar: "متخصص / مستشار" },

  // ── Forgot/Reset Password ────────────────────────────────────────────────────
  "forgot.title":           { en: "Forgot Password",         ar: "نسيت كلمة المرور" },
  "forgot.subtitle":        { en: "Enter your email and we'll send you a reset code.", ar: "أدخل بريدك الإلكتروني وسنرسل لك رمز إعادة التعيين." },
  "forgot.email":           { en: "Email Address",           ar: "البريد الإلكتروني" },
  "forgot.send":            { en: "Send Reset Code",         ar: "إرسال رمز الاسترداد" },
  "forgot.sending":         { en: "Sending...",              ar: "جاري الإرسال..." },
  "forgot.backLogin":       { en: "Back to Login",           ar: "العودة لتسجيل الدخول" },
  "reset.title":            { en: "Reset Password",          ar: "إعادة تعيين كلمة المرور" },
  "reset.code":             { en: "Reset Code",              ar: "رمز الاسترداد" },
  "reset.newPassword":      { en: "New Password",            ar: "كلمة المرور الجديدة" },
  "reset.confirm":          { en: "Confirm New Password",    ar: "تأكيد كلمة المرور الجديدة" },
  "reset.submit":           { en: "Reset Password",          ar: "إعادة تعيين كلمة المرور" },

  // ── Experts ─────────────────────────────────────────────────────────────────
  "experts.title":          { en: "Consult our",             ar: "استشر" },
  "experts.titleAccent":    { en: "Experts",                 ar: "خبراءنا" },
  "experts.subtitle":       { en: "Connect with certified agricultural specialists and expert advisors.", ar: "تواصل مع متخصصين زراعيين معتمدين ومستشارين خبراء." },
  "experts.search":         { en: "Search by specialty or name...", ar: "البحث بالتخصص أو الاسم..." },
  "experts.createCard":     { en: "Create Expert Card",      ar: "إنشاء بطاقة خبير" },
  "experts.hourlyRate":     { en: "Hourly Rate",             ar: "السعر بالساعة" },
  "experts.viewProfile":    { en: "View Profile",            ar: "عرض الملف" },
  "experts.location":       { en: "Location",                ar: "الموقع" },
  "experts.degree":         { en: "Degree",                  ar: "المؤهل" },
  "experts.experience":     { en: "Experience",              ar: "الخبرة" },
  "experts.years":          { en: "Years",                   ar: "سنوات" },
  "experts.consult":        { en: "Start Free Consultation", ar: "ابدأ استشارة مجانية" },
  "experts.reviews":        { en: "reviews",                 ar: "تقييم" },
  "experts.createTitle":    { en: "Create Expert Listing",   ar: "إنشاء إعلان خبير" },
  "experts.createSub":      { en: "Approved experts can publish their profile card in the Experts marketplace.", ar: "يمكن للخبراء المعتمدين نشر بطاقتهم في سوق الخبراء." },
  "experts.listingTitle":   { en: "Listing title",           ar: "عنوان الإعلان" },
  "experts.specialty":      { en: "Specialty",               ar: "التخصص" },
  "experts.descPlaceholder":{ en: "Describe your expertise and services", ar: "صف خبرتك وخدماتك" },
  "experts.hourlyPlaceholder":{ en: "Hourly rate",           ar: "السعر بالساعة" },
  "experts.locationPlaceholder":{ en: "Location",            ar: "الموقع" },
  "experts.imageUrl":       { en: "Image URL (optional)",    ar: "رابط الصورة (اختياري)" },
  "experts.publish":        { en: "Publish Expert Card",     ar: "نشر بطاقة الخبير" },
  "experts.created":        { en: "Expert card created successfully.", ar: "تم إنشاء بطاقة الخبير بنجاح." },
  "experts.requiredFields": { en: "Please complete all required fields.", ar: "يرجى إكمال جميع الحقول المطلوبة." },
  "experts.loading":        { en: "Loading experts...",      ar: "جاري تحميل الخبراء..." },

  // ── Notifications ────────────────────────────────────────────────────────────
  "notif.title":            { en: "Action Center",           ar: "مركز الإجراءات" },
  "notif.subtitle":         { en: "Zar3a Intelligence Hub",  ar: "مركز زرعة الذكي" },
  "notif.total":            { en: "total",                   ar: "إجمالي" },
  "notif.markRead":         { en: "Mark Read",               ar: "تعليم كمقروء" },
  "notif.filter.all":       { en: "All",                     ar: "الكل" },
  "notif.filter.unread":    { en: "Unread",                  ar: "غير مقروء" },
  "notif.filter.order":     { en: "Orders",                  ar: "الطلبات" },
  "notif.filter.system":    { en: "System",                  ar: "النظام" },
  "notif.empty":            { en: "No Notifications",        ar: "لا توجد إشعارات" },
  "notif.emptyDesc":        { en: "Everything is running smoothly in your field.", ar: "كل شيء يسير بسلاسة في حقلك." },
  "notif.qty":              { en: "Qty:",                    ar: "الكمية:" },
  "notif.preferences":      { en: "Preferences",             ar: "التفضيلات" },
  "notif.orderPref":        { en: "Order Notifications",     ar: "إشعارات الطلبات" },
  "notif.orderPrefDesc":    { en: "Get notified when orders are placed", ar: "احصل على إشعارات عند وضع الطلبات" },
  "notif.productPref":      { en: "Product Notifications",   ar: "إشعارات المنتجات" },
  "notif.productPrefDesc":  { en: "Get notified when new products are added", ar: "احصل على إشعارات عند إضافة منتجات جديدة" },
  "notif.prefInfo":         { en: "Modifying these settings affects how you receive critical alerts for your marketplace activity.", ar: "يؤثر تعديل هذه الإعدادات على طريقة تلقيك للتنبيهات المهمة." },
  "notif.save":             { en: "Save Changes",            ar: "حفظ التغييرات" },
  "notif.justNow":          { en: "Just now",                ar: "الآن" },

  // ── Marketplace ──────────────────────────────────────────────────────────────
  "market.title":           { en: "Marketplace",             ar: "السوق" },
  "market.subtitle":  { en: "Your complete agricultural trading hub", ar: "مركزك الزراعي الشامل للتداول" },
  "market.search":    { en: "Search products...",      ar: "البحث عن منتجات..." },
  "market.all":       { en: "All",                     ar: "الكل" },
  "market.addToCart": { en: "Add to cart",             ar: "أضف إلى السلة" },
  "market.outOfStock":{ en: "Out of Stock",            ar: "نفد المخزون" },
  "market.price":     { en: "Price",                   ar: "السعر" },
  "market.unit":      { en: "Unit",                    ar: "الوحدة" },
  "market.seller":    { en: "Seller",                  ar: "البائع" },
  "market.verified":  { en: "Verified",                ar: "موثّق" },
  "market.viewCart":  { en: "View Cart",               ar: "عرض السلة" },
  "market.cart":      { en: "Cart",                    ar: "السلة" },
  "market.cartEmpty": { en: "Your cart is empty",      ar: "سلتك فارغة" },
  "market.checkout":  { en: "Checkout",                ar: "إتمام الشراء" },
  "market.remove":    { en: "Remove",                  ar: "إزالة" },
  "market.total":     { en: "Total",                   ar: "الإجمالي" },
  "market.items":     { en: "items",                   ar: "منتجات" },
  "market.noProducts":{ en: "No products found",       ar: "لا توجد منتجات" },
  "market.addProduct":{ en: "Add Product",             ar: "إضافة منتج" },
  "market.listProduct":{ en: "List a Product",          ar: "أضف منتجاً" },
  "market.productName":{ en: "Product Name",            ar: "اسم المنتج" },
  "market.category":  { en: "Category",                ar: "الفئة" },
  "market.description":{ en: "Description",             ar: "الوصف" },
  "market.loginToAdd":{ en: "Login to add to cart",    ar: "سجل دخولك لإضافة للسلة" },
  "market.region":          { en: "Region",                  ar: "المنطقة" },
  "market.closeFilters":    { en: "Close Filters",           ar: "إغلاق التصفية" },
  "market.openFilters":     { en: "Open Filters",            ar: "فتح التصفية" },
  "market.sortBy":          { en: "Sort By",                 ar: "ترتيب حسب" },
  "market.maxPrice":        { en: "Max Price",               ar: "الحد الأقصى للسعر" },
  "market.clearFilters":    { en: "Clear Filters",           ar: "مسح التصفية" },
  "market.noItemsFound":    { en: "No items found matching your filters.", ar: "لم يتم العثور على سلع تطابق اختياراتك." },
  "market.unitPrice":       { en: "Unit Price",              ar: "سعر الوحدة" },
  "market.totalEstimate":   { en: "Total Estimate",          ar: "التقدير الإجمالي" },
  "market.checkoutSecure":  { en: "Checkout Securely",       ar: "إتمام الدفع بأمان" },
  "market.addMarketProd":   { en: "Add Marketplace Product", ar: "إضافة منتج للسوق" },
  "market.addMarketDesc":   { en: "Suppliers and farmers can list products directly in the marketplace.", ar: "يمكن للموردين والمزارعين إدراج المنتجات مباشرة في السوق." },
  "market.prodTitle":       { en: "Product title",           ar: "عنوان المنتج" },
  "market.prodDesc":        { en: "Product description",     ar: "وصف المنتج" },
  "market.manual":          { en: "Manual",                  ar: "يدوي" },
  "market.sensed":          { en: "Sensed",                  ar: "مستشعر" },
  "market.available":       { en: "Available",               ar: "متاح" },
  "market.sold":            { en: "Sold",                    ar: "مباع" },
  "market.deleted":         { en: "Deleted",                 ar: "محذوف" },
  "market.createListing":   { en: "Create Listing",          ar: "إنشاء الإعلان" },
  "market.edit":            { en: "Edit Product",            ar: "تعديل المنتج" },

  // ── Track Orders ─────────────────────────────────────────────────────────────
  "track.title":      { en: "Track Orders",            ar: "تتبع الطلبات" },
  "track.subtitle":   { en: "Live order fulfillment monitoring", ar: "مراقبة الطلبات مباشرة" },
  "track.noOrders":   { en: "No orders found",         ar: "لا توجد طلبات" },
  "track.status.pending":   { en: "Pending",                 ar: "قيد الانتظار" },
  "track.status.processed": { en: "Processed",               ar: "تمت المعالجة" },
  "track.status.shipped":   { en: "Shipped",                 ar: "تم الشحن" },
  "track.status.delivered": { en: "Delivered",               ar: "تم التسليم" },
  "track.orderId":    { en: "Order ID",                ar: "رقم الطلب" },
  "track.product":    { en: "Product",                 ar: "المنتج" },
  "track.quantity":   { en: "Quantity",                ar: "الكمية" },
  "track.orderDate":  { en: "Order Date",              ar: "تاريخ الطلب" },
  "track.feed":             { en: "Order & Product Feed",    ar: "تغذية الطلبات والمنتجات" },
  "track.feedDesc":         { en: "All products from Crop Market and Agri Market, aggregated for Admin, Farmer, and Supplier users.", ar: "جميع المنتجات من سوق المحاصيل ومتجر الزراعة، مجمعة للمسؤول والمزارع والمورد." },
  "track.refresh":          { en: "Refresh",                 ar: "تحديث" },
  "track.search":           { en: "Search orders or products", ar: "البحث عن الطلبات أو المنتجات" },
  "track.totalItems":       { en: "Total items",             ar: "إجمالي السلع" },
  "track.showingAll":       { en: "Showing products across all marketplaces and roles", ar: "عرض المنتجات عبر جميع الأسواق والأدوار" },
  "track.loading":          { en: "Loading order tracking...", ar: "جاري تحميل تتبع الطلبات..." },
  "track.noTrackedItems":   { en: "No tracked items found.", ar: "لم يتم العثور على أي سلع متتبعة." },
  "track.noDesc":           { en: "No description provided.", ar: "لا يوجد وصف متوفر." },
  "track.denied":           { en: "Access Denied",           ar: "تم رفض الوصول" },
  "track.deniedDesc":       { en: "Buyers and Agro Experts cannot access the Track Orders page. Please visit another section.", ar: "المشترون والخبراء الزراعيون لا يمكنهم تتبع الطلبات. يرجى زيارة قسم آخر." },
  "track.goDash":           { en: "Go to Dashboard",         ar: "الذهاب للوحة التحكم" },

  // ── AI Assistant ─────────────────────────────────────────────────────────────
  "ai.title":         { en: "AI Farming Assistant",   ar: "مساعد زرعة الذكي" },
  "ai.subtitle":      { en: "Powered by Groq LLaMA",  ar: "مدعوم بـ Groq LLaMA" },
  "ai.send":          { en: "Send",                   ar: "إرسال" },
  "ai.placeholder":   { en: "Ask about crops, diseases, fertilizers...", ar: "اسأل عن المحاصيل والأمراض والأسمدة..." },
  "ai.typing":        { en: "Analyzing...",            ar: "جاري التحليل..." },
  "ai.clearChat":     { en: "Clear Chat",             ar: "مسح المحادثة" },
  "ai.noKey":         { en: "⚠️ AI Assistant Not Configured", ar: "⚠️ المساعد الذكي غير مُهيّأ" },
  "ai.noKeyDesc":     { en: "The GROQ API key is missing.", ar: "مفتاح GROQ API غير موجود." },

  // ── Settings ─────────────────────────────────────────────────────────────────
  "settings.title":   { en: "Settings",               ar: "الإعدادات" },
  "settings.subtitle":{ en: "Manage your preferences", ar: "إدارة تفضيلاتك" },
  "settings.appearance":{ en: "Appearance",             ar: "المظهر" },
  "settings.language":{ en: "Language",               ar: "اللغة" },
  "settings.account": { en: "Account",                ar: "الحساب" },
  "settings.security":{ en: "Security",               ar: "الأمان" },
  "settings.save":    { en: "Save",                   ar: "حفظ" },
  "settings.darkMode":{ en: "Dark Mode",              ar: "الوضع الداكن" },
  "settings.lightMode":{ en: "Light Mode",             ar: "الوضع الفاتح" },
  "settings.arabic":  { en: "Arabic",                 ar: "العربية" },
  "settings.english": { en: "English",                ar: "الإنجليزية" },
  "settings.profileTab":    { en: "Profile",                ar: "الملف الشخصي" },
  "settings.notifTab":      { en: "Notifications",           ar: "الإشعارات" },
  "settings.signout":       { en: "Sign Out",               ar: "تسجيل الخروج" },
  "settings.deleteAcc":     { en: "Delete Account?",        ar: "حذف الحساب؟" },
  "settings.deleteAccDesc": { en: "This action is irreversible. All your data will be lost.", ar: "هذا الإجراء لا يمكن التراجع عنه. ستفقد جميع بياناتك." },
  "settings.logoutConfirm": { en: "Are you sure you want to log out of Zar3a?", ar: "هل أنت متأكد من تسجيل الخروج من زرعة؟" },
  "settings.cancel":        { en: "Cancel",                 ar: "إلغاء" },
  "settings.confirm":       { en: "Confirm",                ar: "تأكيد" },
  "settings.desc":          { en: "Manage your Zar3a profile, security, and system preferences.", ar: "إدارة ملفك الشخصي وأمانك وتفضيلات النظام في زرعة." },
  "settings.avatarDesc":    { en: "Click the avatar to upload a new image. Max 5MB.", ar: "اضغط على الصورة الرمزية لتحميل صورة جديدة. الحد الأقصى 5 ميجابايت." },
  "settings.fullName":      { en: "Full Name",               ar: "الاسم الكامل" },
  "settings.phone":         { en: "Phone",                  ar: "الهاتف" },
  "settings.email":         { en: "Email Address",           ar: "البريد الإلكتروني" },
  "settings.sessions":      { en: "Active Sessions",         ar: "الجلسات النشطة" },
  "settings.noSessions":    { en: "No active sessions found.", ar: "لم يتم العثور على جلسات نشطة." },
  "settings.current":       { en: "Current",                ar: "الحالية" },
  "settings.activeNow":     { en: "Active now",             ar: "نشط الآن" },
  "settings.revoke":        { en: "Revoke",                 ar: "إنهاء الجلسة" },
  "settings.changePass":    { en: "Change Password",         ar: "تغيير كلمة المرور" },
  "settings.currPass":      { en: "Current Password",        ar: "كلمة المرور الحالية" },
  "settings.newPass":       { en: "New Password",            ar: "كلمة المرور الجديدة" },
  "settings.updatePass":    { en: "Update Password",         ar: "تحديث كلمة المرور" },
  "settings.smsAlerts":     { en: "Critical SMS Alerts",     ar: "تنبيهات الرسائل القصيرة الهامة" },
  "settings.smsDesc":       { en: "Receive immediate text messages for hardware failures.", ar: "تلقي رسائل نصية فورية لأعطال الأجهزة." },
  "settings.emailAlerts":   { en: "Daily Email Reports",     ar: "التقارير اليومية عبر البريد الإلكتروني" },
  "settings.emailDesc":     { en: "A summary of Zar3a AI insights sent to your inbox.", ar: "ملخص لرؤى زرعة الذكية يرسل إلى بريدك الوارد." },
  "settings.themeTitle":    { en: "Interface Theme",         ar: "مظهر الواجهة" },
  "settings.dangerZone":    { en: "Danger Zone",            ar: "منطقة الخطر" },
  "settings.deleteDesc":    { en: "Permanently remove your account and all telemetry data.", ar: "حذف حسابك وجميع بيانات الاستشعار عن بعد بشكل دائم." },
  "settings.savePref":      { en: "Save Preferences",        ar: "حفظ التفضيلات" },
  "settings.saving":        { en: "Saving...",               ar: "جاري الحفظ..." },
  "settings.picTitle":      { en: "Profile Picture",         ar: "الصورة الشخصية" },

  // ── Admin ────────────────────────────────────────────────────────────────────
  "admin.title":      { en: "Admin Panel",            ar: "لوحة الإدارة" },
  "admin.subtitle":   { en: "Platform management console", ar: "وحدة التحكم في المنصة" },
  "admin.pending":    { en: "Pending Approvals",      ar: "الطلبات المعلقة" },
  "admin.approve":    { en: "Approve",                ar: "قبول" },
  "admin.reject":     { en: "Reject",                 ar: "رفض" },
  "admin.users":      { en: "All Users",              ar: "جميع المستخدمين" },
  "admin.role":       { en: "Role",                   ar: "الدور" },
  "admin.status":     { en: "Status",                 ar: "الحالة" },
  "admin.active":     { en: "Active",                 ar: "نشط" },
  "admin.inactive":   { en: "Inactive",               ar: "غير نشط" },
  "admin.verified":   { en: "Verified",               ar: "موثّق" },
  "admin.notVerified":{ en: "Not Verified",           ar: "غير موثّق" },
  "admin.approved":   { en: "Approved",               ar: "معتمد" },
  "admin.notApproved":{ en: "Pending",                ar: "معلق" },
  "admin.manageUsers":      { en: "Manage Users & Marketplace", ar: "إدارة المستخدمين والسوق" },
  "admin.manageDesc":       { en: "View every user, change roles, and delete accounts immediately in the database.", ar: "عرض كل مستخدم وتغيير الأدوار وحذف الحسابات مباشرة في قاعدة البيانات." },
  "admin.prodDash":         { en: "Product Dashboard",      ar: "لوحة تحكم المنتجات" },
  "admin.backDash":         { en: "Back to dashboard",       ar: "العودة للوحة التحكم" },
  "admin.totalUsers":       { en: "Total Users",            ar: "إجمالي المستخدمين" },
  "admin.usersDesc":        { en: "All registered users in the system with roles and account status.", ar: "جميع المستخدمين المسجلين في النظام بالأدوار وحالة الحساب." },
  "admin.activeProducts":   { en: "Active Products",        ar: "المنتجات النشطة" },
  "admin.prodDesc":         { en: "Products currently available from both Crop and Agri marketplaces.", ar: "المنتجات المتاحة حالياً في كل من أسواق المحاصيل والمستلزمات." },
  "admin.pendingDesc":      { en: "Expert account requests waiting for review.", ar: "طلبات حسابات الخبراء قيد المراجعة." },
  "admin.usersTable":       { en: "Users",                  ar: "المستخدمون" },
  "admin.usersTableDesc":   { en: "Edit roles and remove users directly from the database.", ar: "تعديل الأدوار وإزالة المستخدمين مباشرة من قاعدة البيانات." },
  "admin.tableName":        { en: "Name",                   ar: "الاسم" },
  "admin.tableEmail":       { en: "Email",                  ar: "البريد الإلكتروني" },
  "admin.tableRole":        { en: "Role",                   ar: "الدور" },
  "admin.tableStatus":      { en: "Status",                 ar: "الحالة" },
  "admin.tableActions":     { en: "Actions",                ar: "الإجراءات" },
  "admin.delete":           { en: "Delete",                 ar: "حذف" },
  "admin.pendingRequests":  { en: "Pending Expert Requests", ar: "طلبات الخبراء المعلقة" },
  "admin.pendingTableDesc": { en: "Review new specialist applications and approve or reject them.", ar: "مراجعة طلبات المتخصصين الجديدة وقبولها أو رفضها." },
  "admin.noPending":        { en: "No pending requests at the moment.", ar: "لا توجد طلبات معلقة حالياً." },
  "admin.degree":           { en: "Degree",                  ar: "الدرجة" },
  "admin.experience":       { en: "Experience",              ar: "الخبرة" },
  "admin.bio":              { en: "Bio",                    ar: "السيرة" },
  "admin.viewCv":           { en: "View CV file",            ar: "عرض السيرة الذاتية" },
  "admin.loading":          { en: "Loading admin dashboard...", ar: "جاري تحميل لوحة الإدارة..." },
  "admin.loadingDesc":      { en: "Please wait while your admin workspace loads.", ar: "يرجى الانتظار أثناء تحميل لوحة الإدارة." },
  "admin.authRequired":     { en: "Authentication Required", ar: "التوثيق مطلوب" },
  "admin.loginToAccess":    { en: "Please log in to access the admin dashboard.", ar: "يرجى تسجيل الدخول للوصول إلى لوحة الإدارة." },
  "admin.accessDenied":     { en: "Access Denied",           ar: "تم رفض الوصول" },
  "admin.noPermission":     { en: "You don't have permission to access this section.", ar: "ليس لديك صلاحية للوصول إلى هذا القسم." },
  "admin.backToDashboard":  { en: "Back to Dashboard",       ar: "العودة للوحة التحكم" },
  "admin.selectRole":       { en: "Select role",             ar: "اختر الدور" },
  "admin.roleAdmin":        { en: "Admin",                   ar: "المسؤول" },
  "admin.roleFarmer":       { en: "Farmer",                  ar: "المزارع" },
  "admin.roleSupplier":      { en: "Supplier",                ar: "المورد" },
  "admin.roleBuyer":         { en: "Buyer",                   ar: "المشتري" },
  "admin.roleExpert":        { en: "Agro Expert",             ar: "الخبير الزراعي" },
  "admin.roleUnassigned":    { en: "Unassigned",              ar: "غير معين" },
  "admin.statusActive":      { en: "Active",                  ar: "نشط" },
  "admin.statusInactive":    { en: "Inactive",                ar: "غير نشط" },
  "admin.cvNA":              { en: "N/A",                     ar: "غير متوفر" },
  "admin.noBio":             { en: "No bio provided.",        ar: "لم يتم تقديم سيرة ذاتية." },
  "admin.cvYears":           { en: "years",                   ar: "سنوات" },


  // ── Dashboard ────────────────────────────────────────────────────────────────
  "dash.title":       { en: "Farm Dashboard",         ar: "لوحة تحكم المزرعة" },
  "dash.subtitle":    { en: "Smart analytics & insights", ar: "تحليلات ورؤى ذكية" },
  "dash.totalRevenue":{ en: "Total Revenue",          ar: "إجمالي الإيرادات" },
  "dash.totalOrders": { en: "Total Orders",           ar: "إجمالي الطلبات" },
  "dash.products":    { en: "Products",               ar: "المنتجات" },
  "dash.activeListings":{ en: "Active Listings",        ar: "الإعلانات النشطة" },
  "dash.recentActivity":{ en: "Recent Activity",        ar: "النشاط الأخير" },
  "dash.salesChart":  { en: "Sales Overview",         ar: "نظرة عامة على المبيعات" },
  "dash.revenue":     { en: "Revenue",                ar: "الإيرادات" },
  "dash.orders":      { en: "Orders",                 ar: "الطلبات" },
  "dash.systemLogs":        { en: "System Logs",            ar: "سجلات النظام" },
  "dash.zoneLocation":      { en: "Zone Location",           ar: "موقع المنطقة" },
  "dash.sector":            { en: "Sector",                  ar: "القطاع" },
  "dash.greenhouse":        { en: "Greenhouse",              ar: "الصوبة الزراعية" },
  "dash.openField":         { en: "Open Field",              ar: "الحقل المفتوح" },
  "dash.nileBasin":         { en: "Nile Basin",              ar: "حوض النيل" },
  "dash.deltaOrchard":      { en: "Delta Orchard",           ar: "بستان الدلتا" },
  "dash.best":              { en: "Best",                   ar: "أفضل" },
  "dash.mode":              { en: "Mode",                   ar: "الوضع" },
  "dash.auto":              { en: "Auto",                   ar: "تلقائي" },
  "dash.manual":            { en: "Manual",                  ar: "يدوي" },
  "dash.hardwareControl":   { en: "Hardware Control",       ar: "التحكم في الأجهزة" },
  "dash.pump":              { en: "Pump",                   ar: "المضخة" },
  "dash.vent":              { en: "Vent",                   ar: "التهوية" },
  "dash.fertilizer":        { en: "Fertilizer",             ar: "التسميد" },
  "dash.liveClimate":       { en: "Live Climate",           ar: "المناخ المباشر" },
  "dash.region":            { en: "Region",                  ar: "المنطقة" },
  "dash.aiSuggested":       { en: "AI Suggested",           ar: "مقترح بالذكاء" },
  "dash.moistureTelemetry": { en: "Moisture Telemetry",     ar: "بيانات رطوبة التربة" },
  "dash.pumpStatus":        { en: "Pump Status",            ar: "حالة المضخة" },
  "dash.aiEngine":          { en: "AI Engine",              ar: "محرك الذكاء الاصطناعي" },
  "dash.viewProfileRevenue":{ en: "View Profile & Revenue",  ar: "عرض الملف المالي والإيرادات" },
  "dash.financialProj":     { en: "Financial Projection",   ar: "التوقعات المالية" },
  "dash.expectedYield":     { en: "Expected Yield",         ar: "الإنتاج المتوقع" },
  "dash.marketPrice":       { en: "Market Price",           ar: "سعر السوق" },
  "dash.careThreats":       { en: "Care & Threats",          ar: "الرعاية والتهديدات" },
  "dash.nutrients":         { en: "Nutrients",               ar: "المغذيات" },
  "dash.commonDiseases":    { en: "Common Diseases",         ar: "الأمراض الشائعة" },

  // Crops
  "crop.Cotton":            { en: "Cotton",                  ar: "القطن" },
  "crop.Wheat":             { en: "Wheat",                  ar: "القمح" },
  "crop.Sugar Cane":        { en: "Sugar Cane",              ar: "قصب السكر" },
  "crop.Tomato":            { en: "Tomato",                  ar: "الطماطم" },
  "crop.Citrus":            { en: "Citrus",                  ar: "الحمضيات" },
  "crop.Rice":              { en: "Rice",                    ar: "الأرز" },
  "crop.Maize":             { en: "Maize",                   ar: "الذرة" },
  "crop.Potato":            { en: "Potato",                  ar: "البطاطس" },
  "crop.Clover":            { en: "Clover",                  ar: "البرسيم" },
  "crop.Onion":             { en: "Onion",                   ar: "البصل" },

  // Locations / Regions
  "loc.Cairo, Greater Cairo": { en: "Cairo, Greater Cairo",  ar: "القاهرة، القاهرة الكبرى" },
  "loc.Dakahlia, Mansoura":  { en: "Dakahlia, Mansoura",      ar: "الدقهلية، المنصورة" },
  "loc.Minya, Upper Egypt":  { en: "Minya, Upper Egypt",      ar: "المنيا، صعيد مصر" },
  "loc.Aswan, Deep South":   { en: "Aswan, Deep South",       ar: "أسوان، أقصى الجنوب" },
  "loc.Alexandria, Coast":   { en: "Alexandria, Coast",       ar: "الإسكندرية، الساحل" },
  "loc.Sharqia, Delta":      { en: "Sharqia, Delta",          ar: "الشرقية، الدلتا" },
  "loc.Beheira, West Delta": { en: "Beheira, West Delta",     ar: "البحيرة، غرب الدلتا" },
  "loc.Fayoum, Oasis":       { en: "Fayoum, Oasis",           ar: "الفيوم، الواحات" },
  "loc.Gharbia, Central Delta": { en: "Gharbia, Central Delta", ar: "الغربية، وسط الدلتا" },
  "loc.Kafr El Sheikh, North Delta": { en: "Kafr El Sheikh, North Delta", ar: "كفر الشيخ، شمال الدلتا" },

  "reg.Capital":            { en: "Capital",                 ar: "العاصمة" },
  "reg.Delta":              { en: "Delta",                   ar: "الدلتا" },
  "reg.Middle Egypt":       { en: "Middle Egypt",            ar: "مصر الوسطى" },
  "reg.South Upper Egypt":  { en: "South Upper Egypt",       ar: "جنوب صعيد مصر" },
  "reg.Coastal":            { en: "Coastal",                 ar: "ساحلي" },
  "reg.West Delta":         { en: "West Delta",              ar: "غرب الدلتا" },
  "reg.Oasis":              { en: "Oasis",                   ar: "الواحات" },
  "reg.Central Delta":      { en: "Central Delta",           ar: "وسط الدلتا" },
  "reg.North Delta":        { en: "North Delta",             ar: "شمال الدلتا" },
  "reg.Egypt":              { en: "Egypt",                   ar: "مصر" },

  // Weather conditions
  "weather.Clear Sky":      { en: "Clear Sky",               ar: "سماء صافية" },
  "weather.Partly Cloudy":  { en: "Partly Cloudy",           ar: "غائم جزئياً" },
  "weather.Foggy":          { en: "Foggy",                   ar: "ضبابي" },
  "weather.Rainy":          { en: "Rainy",                   ar: "ممطر" },
  "weather.Sunny":          { en: "Sunny",                   ar: "مشمش" },
  "weather.Offline":        { en: "Offline",                 ar: "غير متصل" },

  // System Logs
  "log.boot":               { en: "System Booted Successfully", ar: "تم تشغيل النظام بنجاح" },
  "log.mode":               { en: "Mode changed",            ar: "تم تغيير الوضع" },
  "log.manualOn":           { en: "turned ON",               ar: "قيد التشغيل" },
  "log.manualOff":          { en: "turned OFF",              ar: "مغلق" },

  // Advice states
  "advice.irrigating":      { en: "Irrigating to reach",     ar: "جاري الري للوصول إلى" },
  "advice.critical":        { en: "CRITICAL: Dry soil. At",  ar: "حرِج: تربة جافة. عند" },
  "advice.criticalEnd":     { en: "°C, evaporation is fast. Turn on pumps!", ar: "درجة مئوية، التبخر سريع. شغل المضخات!" },
  "advice.warning":         { en: "WARNING: Waterlogging detected. Stop irrigation.", ar: "تحذير: تم اكتشاف تشبع بالمياه. أوقف الري." },
  "advice.optimal":         { en: "Optimal conditions for",  ar: "ظروف مثالية لـ" },
  "advice.optimalEnd":      { en: ". Environment is balanced.", ar: ". البيئة متوازنة." },

  // Pump status
  "pump.idle":              { en: "Idle",                    ar: "خامل" },
  "pump.active":            { en: "Active",                  ar: "نشط" },
  "pump.activeStop":        { en: "Active (Consider Stopping)", ar: "نشط (يفضل الإيقاف)" },
  "pump.critical":          { en: "Critical (Needs Pump)",   ar: "حرج (يحتاج ري)" },
  "pump.halted":            { en: "Halted",                  ar: "متوقف" },
  "pump.standby":           { en: "Standby",                 ar: "في الانتظار" },

  // ── Products Dashboard ────────────────────────────────────────────────────────
  "prodDash.title":   { en: "Product Dashboard",      ar: "لوحة المنتجات" },
  "prodDash.addProduct":{ en: "Add Product",            ar: "إضافة منتج" },
  "prodDash.myProducts":{ en: "My Products",            ar: "منتجاتي" },
  "prodDash.noProducts":{ en: "No products yet",        ar: "لا توجد منتجات بعد" },
  "prodDash.edit":    { en: "Edit",                   ar: "تعديل" },
  "prodDash.delete":  { en: "Delete",                 ar: "حذف" },
  "prodDash.stock":   { en: "Stock",                  ar: "المخزون" },
  "prodDash.category":{ en: "Category",               ar: "الفئة" },
  "prodDash.refresh":       { en: "Refresh",                 ar: "تحديث" },
  "prodDash.browseMarket":  { en: "Browse Marketplace",     ar: "تصفح السوق" },
  "prodDash.allItems":      { en: "All Items",              ar: "جميع السلع" },
  "prodDash.cropProd":      { en: "Crop Products",           ar: "منتجات المحاصيل" },
  "prodDash.agriShop":      { en: "Agri Shop",               ar: "متجر الزراعة" },
  "prodDash.cropMarket":    { en: "Crop Market",             ar: "سوق المحاصيل" },
  "prodDash.seller":        { en: "Seller",                  ar: "البائع" },
  "prodDash.region":        { en: "Region",                  ar: "المنطقة" },
  "prodDash.status":        { en: "Status",                 ar: "الحالة" },
  "prodDash.price":         { en: "Price",                   ar: "السعر" },
  "prodDash.viewOnly":      { en: "VIEW ONLY",               ar: "عرض فقط" },
  "prodDash.noProductsFound": { en: "No products found",     ar: "لم يتم العثور على منتجات" },
  "prodDash.noProductsDesc": { en: "No products matched the search query or filters currently selected.", ar: "لا توجد منتجات تطابق شروط البحث أو التصفية الحالية." },
  "prodDash.manageOffer":   { en: "Manage & Monitor Marketplace Offerings", ar: "إدارة ومراقبة معروضات السوق" },
  "prodDash.searchPlaceholder": { en: "Search products by title, category, region...", ar: "البحث عن المنتجات بالاسم، الفئة، المنطقة..." },
  "prodDash.loading":       { en: "Loading products...",      ar: "جاري تحميل المنتجات..." },
  "prodDash.confirmDelete": { en: "Are you sure you want to delete this product?", ar: "هل أنت متأكد من حذف هذا المنتج؟" },
  "prodDash.deleteSuccess": { en: "Product deleted successfully.", ar: "تم حذف المنتج بنجاح." },
  "prodDash.loadFailed":    { en: "Failed to retrieve marketplace products.", ar: "فشل استرداد منتجات السوق." },
  "prodDash.deleteFailed":    { en: "Failed to delete product.", ar: "فشل حذف المنتج." },


  // ── Profiles ─────────────────────────────────────────────────────────────────
  "profile.farmer":         { en: "Farmer",                  ar: "مزارع" },
  "profile.buyer":          { en: "Buyer",                   ar: "مشترٍ" },
  "profile.supplier":       { en: "Supplier",                ar: "مورّد" },
  "profile.expert":         { en: "Agro-Expert",             ar: "خبير زراعي" },
  "profile.personalInfo":   { en: "Personal Information",    ar: "المعلومات الشخصية" },
  "profile.fullName":       { en: "Full Name",               ar: "الاسم الكامل" },
  "profile.username":       { en: "Username",                ar: "اسم المستخدم" },
  "profile.email":          { en: "Email",                   ar: "البريد الإلكتروني" },
  "profile.phone":          { en: "Phone",                  ar: "الهاتف" },
  "profile.farmInfo":       { en: "Farm Information",        ar: "معلومات المزرعة" },
  "profile.farmSize":       { en: "Farm Size",               ar: "مساحة المزرعة" },
  "profile.soilType":       { en: "Soil Type",               ar: "نوع التربة" },
  "profile.location":       { en: "Location",                ar: "الموقع" },
  "profile.quickActions":   { en: "Quick Actions",           ar: "إجراءات سريعة" },
  "profile.memberSince":    { en: "Member Since",            ar: "عضو منذ" },
  "profile.browseProducts": { en: "Browse Products",         ar: "تصفح المنتجات" },
  "profile.consultExperts":  { en: "Consult Experts",         ar: "استشارة الخبراء" },
  "profile.accStatus":      { en: "Account Status",          ar: "حالة الحساب" },
  "profile.active":         { en: "Active",                  ar: "نشط" },
  "profile.role":           { en: "Role",                    ar: "الدور" },
  "profile.downloadCv":     { en: "Download CV",             ar: "تنزيل السيرة الذاتية" },
  "profile.verifiedExpert": { en: "Verified Expert",         ar: "خبير معتمد" },
  "profile.pendingApproval": { en: "Pending Approval",        ar: "قيد الانتظار" },
  "profile.pendingMessage": { en: "Your expert application is pending admin approval. You'll be notified once approved!", ar: "طلب الخبير الخاص بك قيد انتظار موافقة المسؤول. سيتم إعلامك بمجرد الموافقة!" },
  "profile.approvedMessage": { en: "Approved! You are now a verified Agro-Expert on Zar3a.", ar: "تمت الموافقة! أنت الآن خبير زراعي معتمد على زرعة." },
  "profile.consultations":  { en: "Consultations",           ar: "الاستشارات" },
  "profile.credentials":    { en: "Expert Credentials",      ar: "مؤهلات الخبير" },
  "profile.degree":         { en: "Academic Degree",         ar: "المؤهل الأكاديمي" },
  "profile.experience":     { en: "Experience (Years)",      ar: "الخبرة (بالسنوات)" },

  "profile.prodDash":       { en: "Product Dashboard",      ar: "لوحة المنتجات" },
  "profile.trackOrder":     { en: "Track Order",             ar: "تتبع الطلب" },
  "profile.browseMarket":   { en: "Browse Marketplace",     ar: "تصفح السوق" },

  "profile.editProfile":    { en: "Edit Profile",            ar: "تعديل الملف" },
  "profile.bizInfo":        { en: "Business Information",    ar: "معلومات العمل" },
  "profile.tradeLicense":   { en: "Trade License",           ar: "الرخصة التجارية" },
  "profile.status":         { en: "Status",                 ar: "الحالة" },
  "profile.verified":       { en: "Verified",                ar: "موثق" },
  "profile.years":          { en: "years",                   ar: "سنوات" },
  "profile.pendingApp":     { en: "Your expert application is pending admin approval. You'll be notified once approved!", ar: "طلب انضمامك كخبير قيد مراجعة الإدارة. سنقوم بإعلامك بمجرد الموافقة!" },
  "profile.backProfile":    { en: "Back to Profile",         ar: "العودة للملف الشخصي" },
  "profile.consultationRequests": { en: "Consultation Requests", ar: "طلبات الاستشارة" },
  "profile.recentConvs":    { en: "Recent Conversations",    ar: "المحادثات الأخيرة" },
  "profile.contacts":       { en: "contacts",                ar: "جهات اتصال" },
  "profile.noConsultations": { en: "No consultations yet. Once a buyer sends a message, the conversation will appear here.", ar: "لا توجد استشارات بعد. بمجرد أن يرسل المشتري رسالة، ستظهر المحادثة هنا." },

  "profile.approvedMsg":    { en: "Approved! You are now a verified Agro-Expert on Zar3a.", ar: "تمت الموافقة! أنت الآن خبير زراعي معتمد في منصة زرعة." },
  "profile.viewProfile":    { en: "View Profile",            ar: "عرض الملف الشخصي" },
  "profile.accountStatus":  { en: "Account Status",          ar: "حالة الحساب" },
  "profile.noConvsYet":     { en: "No consultations yet. Once a buyer sends a message, the conversation will appear here.", ar: "لا توجد استشارات بعد. بمجرد أن يرسل المشتري رسالة، ستظهر المحادثة هنا." },
  "profile.unread":         { en: "Unread",                  ar: "غير مقروء" },

  // ── Chat ─────────────────────────────────────────────────────────────────────
  "chat.title":       { en: "Messages",               ar: "الرسائل" },
  "chat.placeholder": { en: "Type a message...",      ar: "اكتب رسالة..." },
  "chat.send":        { en: "Send",                   ar: "إرسال" },
  "chat.noMessages":  { en: "No messages yet",        ar: "لا توجد رسائل بعد" },
  "chat.startChat":   { en: "Start the conversation", ar: "ابدأ المحادثة" },
  "chat.online":      { en: "Online",                 ar: "متصل" },
  "chat.activeNow":         { en: "Active Now",             ar: "نشط الآن" },
  "chat.viewDoc":           { en: "View Document",           ar: "عرض المستند" },
  "chat.today":             { en: "Today • Consultation Started", ar: "اليوم • بدأت الاستشارة" },
  "chat.sending":           { en: "SENDING...",              ar: "جاري الإرسال..." },
  "chat.details":           { en: "Expert Details",          ar: "تفاصيل الخبير" },
  "chat.about":             { en: "About",                   ar: "نبذة عن الخبير" },
  "chat.expertChat":        { en: "Expert Chat",             ar: "محادثة الخبير" },


  // ── Payment ──────────────────────────────────────────────────────────────────
  "pay.title":        { en: "Checkout",               ar: "إتمام الشراء" },
  "pay.processing":   { en: "Processing...",          ar: "جاري المعالجة..." },
  "pay.pay":          { en: "Pay Now",                ar: "ادفع الآن" },
  "pay.success":      { en: "Payment Successful!",    ar: "تمت عملية الدفع بنجاح!" },
  "pay.failed":       { en: "Payment Failed",         ar: "فشلت عملية الدفع" },
  "pay.total":        { en: "Total Amount",           ar: "المبلغ الإجمالي" },
  "pay.backCart":           { en: "Back to Cart",            ar: "العودة للسلة" },
  "pay.reviewOrder":        { en: "Review your order",       ar: "راجع طلبك" },
  "pay.secureCheckout":     { en: "Secure Checkout",        ar: "الدفع الآمن" },
  "pay.orderSummary":       { en: "Order Summary",           ar: "ملخص الطلب" },
  "pay.shipping":           { en: "Shipping",               ar: "الشحن" },
  "pay.shippingPlaceholder":{ en: "Enter shipping address or delivery notes", ar: "أدخل عنوان الشحن أو ملاحظات التسليم" },
  "pay.shippingTip":        { en: "Optional but helpful for order fulfillment.", ar: "اختياري ولكنه مفيد لتنفيذ الطلب." },
  "pay.paymentMethod":      { en: "Payment method",          ar: "طريقة الدفع" },
  "pay.card":               { en: "Credit / Debit Card",     ar: "بطاقة الائتمان / الخصم" },
  "pay.totalDue":           { en: "Total due",               ar: "الإجمالي المستحق" },
  "pay.confirmPay":         { en: "Confirm & Pay",           ar: "تأكيد ودفع" },
  "pay.paymentSuccess":     { en: "Payment successful! Your order has been placed.", ar: "نجحت عملية الدفع! تم تقديم طلبك." },
  "pay.paymentError":       { en: "Unable to complete payment. Please try again.", ar: "تعذر إتمام عملية الدفع. يرجى المحاولة مرة أخرى." },


  // ── Not Found ────────────────────────────────────────────────────────────────
  "notFound.title":   { en: "Page Not Found",         ar: "الصفحة غير موجودة" },
  "notFound.subtitle":{ en: "The page you're looking for doesn't exist.", ar: "الصفحة التي تبحث عنها غير موجودة." },
  "notFound.goHome":  { en: "Go Home",                ar: "الصفحة الرئيسية" },
  "notFound.backHome":      { en: "Back Home",               ar: "الرجوع للرئيسية" },
  "notFound.fieldNotFound": { en: "Field Not Found",         ar: "الحقل غير موجود" },
  "notFound.notCultivated": { en: "This area hasn't been cultivated yet. Let's get you back to the fertile lands.", ar: "هذه المنطقة لم تُزرع بعد. فلنعد بك إلى الأراضي الخصبة." },
  "notFound.return":        { en: "Return to Zar3a",         ar: "العودة لـ زرعة" },

  // ── Common ────────────────────────────────────────────────────────────────────
  "common.loading":         { en: "Loading...",             ar: "جاري التحميل..." },
  "common.error":           { en: "An error occurred",      ar: "حدث خطأ" },
  "common.retry":           { en: "Retry",                  ar: "إعادة المحاولة" },
  "common.close":           { en: "Close",                  ar: "إغلاق" },
  "common.cancel":          { en: "Cancel",                 ar: "إلغاء" },
  "common.confirm":         { en: "Confirm",                ar: "تأكيد" },
  "common.save":            { en: "Save",                   ar: "حفظ" },
  "common.edit":            { en: "Edit",                   ar: "تعديل" },
  "common.delete":          { en: "Delete",                 ar: "حذف" },
  "common.add":             { en: "Add",                    ar: "إضافة" },
  "common.search":          { en: "Search",                 ar: "بحث" },
  "common.filter":          { en: "Filter",                 ar: "تصفية" },
  "common.noData":          { en: "No data available",      ar: "لا توجد بيانات" },
  "common.egp":             { en: "EGP",                    ar: "ج.م" },
  "common.perHour":         { en: "/ hr",                   ar: "/ ساعة" },
};

// ─── Context ──────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const lang = "en"; // STRICT ENGLISH CONSTRAINT

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute("dir", "ltr");
    html.setAttribute("lang", "en");
    localStorage.setItem("lang", "en");
  }, []);

  const toggleLang = useCallback(() => {
    // Disabled as per strict English constraint
  }, []);

  const t = useCallback(
    (key) => translations[key]?.["en"] ?? key,
    []
  );

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, isArabic: false }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
};
